### ISSUE TITLE
INSERT OR UPDATE seem unimplemented

### ISSUE THREAD

**Issue by nguyenvancaonguyen** [GoogleCloudPlatform/cloud-spanner-emulator#155]
```
spanner> INSERT OR UPDATE INTO AccountOwnership (AccountOwnershipID, UserID, AccountID, LastUpdateTime) VALUES ("23934e33-608f-5e96-9f5f-2e660bedb923", "cca67cd8-2018-4e4e-b2c5-93234340dd43", "18f77be8-2e6a-45ce-9d49-1326cdd7cf3d", CURRENT_TIMESTAMP());
ERROR: spanner: code = "AlreadyExists", desc = "Table AccountOwnership: Row {String(\"23934e33-608f-5e96-9f5f-2e660bedb923\")} already exists."
```
I try and got similar issue with `INSERT OR IGNORE` and `ON CONFLICT DO ...`

**Comment by olavloite** [comment]
That is correct, it is currently not implemented for the emulator. It is expected to be implemented in one of the next release cycles (so probably 4 to 8 weeks from now).

**Comment by rdss-skirejewski** [comment]
It seems like this was introduced with [1.5.15 ](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/compare/v1.5.14...v1.5.15#diff-8ae394912646f82f0dfff88fc2bea9ec02e4640c506db3b67feb5937d2252911R514)

This breaks our migration scripts, where we use `INSERT` instead of `INSERT OR IGNORE` on an empty table. Is there a way to work around this?

Anyway, thanks for adding it!

**Comment by olavloite** [comment]
> It seems like this was introduced with [1.5.15 ](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/compare/v1.5.14...v1.5.15#diff-8ae394912646f82f0dfff88fc2bea9ec02e4640c506db3b67feb5937d2252911R514)
> 
> This breaks our migration scripts, where we use `INSERT` instead of `INSERT OR IGNORE` on an empty table. Is there a way to work around this?
> 
> Anyway, thanks for adding it!

Sorry, I don't quite understand how it breaks your migration script. Would you mind elaborating a bit?

Or is there a change in how the emulator works if you use a normal `INSERT` statement? If so, then that sounds like a bug.

**Comment by rdss-skirejewski** [comment]
> > It seems like this was introduced with [1.5.15 ](https://github.com/GoogleCloudPlatform/cloud-spanner-emulator/compare/v1.5.14...v1.5.15#diff-8ae394912646f82f0dfff88fc2bea9ec02e4640c506db3b67feb5937d2252911R514)
> > This breaks our migration scripts, where we use `INSERT` instead of `INSERT OR IGNORE` on an empty table. Is there a way to work around this?
> > Anyway, thanks for adding it!
> 
> Sorry, I don't quite understand how it breaks your migration script. Would you mind elaborating a bit?
> 
> Or is there a change in how the emulator works if you use a normal `INSERT` statement? If so, then that sounds like a bug.

One of our scripts tries to fill a table via `INSERT INTO TABLE_A (..) SELECT ..` query which results into a 
```
INTERNAL: ZETASQL_RET_CHECK failure (backend/query/query_engine.cc:521) insert_statement->insert_mode() == zetasql::ResolvedInsertStmt::OR_IGNORE
```
because the table for selection is empty. But using `INSERT IGNORE INTO` works.

Assume `Table A` is empty.

`INSERT INTO B (col1, col2,..) SELECT col1, col2 FROM A` results into the error above.

Using the same Query with `INSERT IGNORE INTO` works with an empty `Table A`. 

If A has atleast one row everything works as before.

**Comment by vieirajlt** [comment]
I am also using `INSERT OR IGNORE` on `1.5.15` to save some rows and I can confirm that, using the same PK, an `AlreadyExists` error is raised.

**Comment by taka-oyama** [comment]
I tried it and it works on `1.5.17`.

**Comment by nguyenvancaonguyen** [comment]
Nice, finally. I will close the ticket.
